### ISSUE TITLE
Need to invistigate cl_teamid_overhead_mode

### ISSUE THREAD

**Issue by JustinBenedick** [LacledesLAN/gamesvr-csgo-tourney#25]
Need to invistigate cl_teamid_overhead_mode.  Its some feature for teammates to be highlights would cut down on teamkilling/damage.

**Comment by TonyDiPietri** [comment]
players said they were unable to change this setting; need to check what normal competitive play allows. setting allows you to see teammate nameplates above their heads

**Comment by dudleycodes** [comment]
Whatever the resolution is, this needs to be added to the rulse
