### ISSUE TITLE
Demo files being written `/app/csgo/` instead of `/app/csgo/logs`

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/gamesvr-csgo-tourney#28]
This might be an exclusive `get5` thing - but let's see if we can get the demo files being written to `/app/csgo/logs` again

**Comment by JustinBenedick** [comment]
Think I might have found a solution. Need to test later
https://splewis.github.io/get5/latest/configuration/#get5_demo_path

get5_demo_path
The folder of saved demo files, relative to the csgo directory. You can use the {MATCHID} and {DATE} variables, i.e. demos/{DATE}/{MATCHID}/. Much like get5_backup_path, the path must not start with a slash, and must end with a slash. Required folders will be created if they do not exist.
Default: ""

**Comment by dudleycodes** [comment]
@JustinBenedick - did you ever test this?

**Comment by JustinBenedick** [comment]
Found this https://splewis.github.io/get5/latest/configuration/#get5_demo_path

**Comment by dudleycodes** [comment]
@JustinBenedick  setting added in get5 config. Needs to be manual tested/verified.

**Comment by JustinBenedick** [comment]
as of 4/29 still persists

**Comment by dudleycodes** [comment]
@JustinBenedick - is this fixed?

**Comment by JustinBenedick** [comment]
Yes from what we saw at the last event
